name: Publish package to the Maven Central Repository
on:
  push:
    branches: [java-maven-rpm]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Maven Build
        run: cd rpm.poc && mvn clean package rpm:rpm
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: List target files
        run: ls -ltra rpm.poc/build/rpm/rpm.poc/RPMS/noarch/