name: Publish package to the Maven Central Repository
on:
  push:
    branches: [java-maven-rpm]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "adopt"
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Maven Build
        run: cd rpm.poc && mvn clean package rpm:rpm

      - name: Check results
        run: tree .

      - uses: actions/upload-artifact@v2
        with:
          name: rpm.poc-artifact
          path: rpm.poc/build/rpm/rpm.poc/RPMS/noarch/rpm.poc-0.0.1-1.noarch.rpm
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v2
        with:
          name: rpm.poc-artifact

      - name: List target files
        run: ls -ltra

      - name: Install RPM
        run: rpm -i rpm.poc-0.0.1-1.noarch.rpm
